# Generated by Django 5.1.3 on 2024-11-09 06:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_advertisement_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertisement',
            name='category',
        ),
        migrations.DeleteModel(
            name='AdvertisementCategory',
        ),
        migrations.AddField(
            model_name='advertisement',
            name='category',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.DO_NOTHING, to='main.category'),
            preserve_default=False,
        ),
    ]
