# Generated by Django 5.1.3 on 2024-11-11 03:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_advertisement_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='post',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.advertisement'),
            preserve_default=False,
        ),
    ]
