# Generated by Django 5.1.3 on 2024-11-11 04:09

import django.contrib.auth.models
import django.db.models.deletion
import main.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_response_post'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='post',
            field=models.ForeignKey(default=main.models.Advertisement, on_delete=django.db.models.deletion.CASCADE, to='main.advertisement'),
        ),
        migrations.AlterField(
            model_name='response',
            name='user',
            field=models.ForeignKey(default=django.contrib.auth.models.User, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
